Universe        = vanilla
Executable      = JetMatSub_Event.sh
notification    = Never
Output          = /sphenix/user/jamesj3j3/analysis/JS-Jet/JetValidation/macro/condorTest2/logs/condorRooUnf$(Process).out
Error           = /sphenix/user/jamesj3j3/analysis/JS-Jet/JetValidation/macro/condorTest2/logs/condorRooUnf$(Process).err
Log             = /tmp/condor_jamesj3j3_$(Process).log
Arguments       = "$(Process)"
Initialdir      = /sphenix/user/jamesj3j3/analysis/JS-Jet/JetValidation/macro/MatchingSubjets/
request_memory = 1100MB
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue 1000
